---
- name: Extract specific columns with custom headers
  hosts: 172.16.3.42
  gather_facts: false
 
  vars:
    source_csv: "/var/lib/awx/projects/ruthupavan/masterlogfile.txt"
    output_csv: "/var/lib/awx/projects/ruthupavan/extracted_5.csv"
 
  tasks:
    - name: Create or empty the output CSV and add custom header
      copy:
        dest: "{{ output_csv }}"
        content: "Call Type,Submit Time,LATENCY,Account Name,SYSTEM ID\n"
 
    - name: Extract columns 1, 3, 32, 55, 56 from source CSV
      shell: |
        awk -F'|' '{print $1","$3","$32","$55","$56}' "{{ source_csv }}" >> "{{ output_csv }}"
      args:
        executable: /bin/bash
